[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.json"

[deploy]
startCommand = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
